### ISSUE TITLE
Minor details 

### ISSUE THREAD

**Issue by petrusen** [radi0sus/xyzoverlay#1]
Hi,

Awesome package, congratulations. I just wanted to add some recommendations so that more people can use it without investing too much time dealing with technical aspects:

**1) Versions:** it would be great to set some specifications on the versions of both python and its dependencies. I created a python environment and below I share the list of what worked for me (e.g., with Python 3.6 I experienced some problems)

Python 3.8.10

contourpy           1.1.1
cycler              0.12.1
fonttools           4.53.1
importlib-resources 6.4.5
kiwisolver          1.4.7
matplotlib          3.7.5
numpy               1.24.4
packaging           24.1
pandas              2.0.3
pillow              10.4.0
pip                 20.0.2
pkg-resources       0.0.0
pyparsing           3.1.4
python-dateutil     2.9.0.post0
pytz                2024.2
scipy               1.10.1
setuptools          44.0.0
six                 1.16.0
tzdata              2024.1
zipp                3.20.2

**2) Downcasting:** line 435 {--> pd.set_option("future.no_silent_downcasting", True)}  got me the following error {pandas._config.config.OptionError: "No such keys(s): 'future.no_silent_downcasting'}. I just commented that line and worked fine, but maybe it deserves a more detailed look.

**3) Test examples:** you show the very nice figures that your code creates, but as far as I know, the original xyz files are not included in the package; as a suggestion, it would be good to include them as test examples to ensure that the package runs smoothly. 

With that being said, thanks again!
Best

Enric

**Comment by radi0sus** [comment]
Hi Eric,

Glad you like it! You make a good point. However, personally, I'm not a fan of using environments for simple scripts. A script that’s just a few KB can end up requiring several hundred MB if it imports libraries like SciPy, NumPy, and Matplotlib. I try to keep the scripts running with the latest versions of Python and the necessary packages until I consider the script outdated or no longer needed. That said, I’ve stopped at Python 3.11 for now because Python 3.12 requires environments by default (at least with the package manager Brew).

I don’t encounter the error with Pandas 2.2.2, no matter whether I comment out the line or not. I believe I added it for a previous version of Pandas (newer than your current one).

I’m not sure where I originally got the sample data from, but I’ll add a link or upload them if I can find them.

Best,
Sebastian

**Comment by petrusen** [comment]
Hi Sebastian,

Thanks for the detailed response! I understand your point about keeping things lightweight and avoiding environments for small scripts. Since I'm using an older version of Pandas, that might explain the difference in behavior regarding the commented-out line.

Regarding Python 3.12 and environments, I appreciate the clarification. It's good to know you've stopped at Python 3.11 for now.

Best,
Enric
